### ISSUE TITLE
Valid time zones for Search Job API

### ISSUE THREAD

**Issue by arknave** [SumoLogic/sumo-api-doc#10]
Is there a list of valid time zones for the search job API? UTC and PST work, but PDT doesn't.

**Comment by davidblondeau** [comment]
Good question, we are using Java's tzdata under the hood (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones). We added a link to the Wikipedia article that lists the time zones supported by the API to our documentation in the errors section and soon in the query parameters section at https://help.sumologic.com/APIs/02Search_Job_API/About_the_Search_Job_API#Errors

Also, our APIs are now officially documented at https://help.sumologic.com/APIs. The pages in this repository have been updated to indicate this change.
