### ISSUE TITLE
API Authentication with email+password is a bad idea...

### ISSUE THREAD

**Issue by shalomc** [SumoLogic/sumo-api-doc#3]
In terms of account security, I would rather see usage of access keys. 
Access keys do not give out full access to account management, and the credentials for the API calls are stored in the scripts that run the APIs. 
Maybe at some point in the future you will develop an authorization scheme like IAM to fine tune permissions.

**Comment by duchatran** [comment]
@shalomc : Thanks for the report, yes you should be able to use access key in place of email/password. Please reopen if this is not the case.
