### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by wliao008** [SumoLogic/sumo-api-doc#4]
curl -u 'user@company.com:password' -X GET https://api.sumologic.com/api/v1/collectors?limit=10 

using my username and password, rec'd error:

{
  "status" : 301,
  "id" : "X62Q5-VNDHN-QNFAK",
  "code" : "moved",
  "message" : "The requested resource SHOULD be accessed through returned URI in Location Header."
}

**Comment by yongxing** [comment]
It says that your account lives in a different deployment and https://api.sumologic.com/api is not the right end point. The correct end point is in the "Location" header and you should access your resource that way.

Adding the "-v" option in your curl command will print out the Location header.

**Comment by wliao008** [comment]
Thanks yongxing!

**Comment by hagurganus** [comment]
+1

**Comment by tskinn** [comment]
+1

**Comment by arnie72** [comment]
+1
