### ISSUE TITLE
From Parameter not working

### ISSUE THREAD

**Issue by drduke1** [SumoLogic/sumo-api-doc#6]
The example provided does not work.

dd-mac:~ dd$ curl -u xxx:yyy "https://api.sumologic.com/api/v1/logs/search?q=error&from=-6h"

{   "status" : 400,   "id" : "TJE9G-SILGQ-0BNXK",   "code" : "search.invalid.timestamp.from",   "message" : "The 'from' field contains an invalid time." }

**Comment by sumoway** [comment]
Relative times are not supported in the REST API.  The wiki documentation was misleading b/c the default for `from` was shown as `-15m`.  It is correct that the default `from` time is *calculated* as 15 minutes ago, but the literal expression `-15m` is not valid.
